# Generated by Django 5.2.6 on 2025-10-14 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledgeprojapp", "0002_emailotp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bonus",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="bonus",
            name="client_email",
        ),
        migrations.RemoveField(
            model_name="bonus",
            name="code",
        ),
        migrations.RemoveField(
            model_name="bonus",
            name="message",
        ),
        migrations.RemoveField(
            model_name="bonus",
            name="transaction_type",
        ),
        migrations.AddField(
            model_name="bonus",
            name="bonus_code",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="bonus",
            name="is_valid",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="bonus",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="knowledgeprojapp.client",
            ),
        ),
    ]
