# Generated by Django 5.2.6 on 2025-10-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledgeprojapp", "0003_rename_created_bonus_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="mimimum_amount",
        ),
        migrations.AddField(
            model_name="plan",
            name="duration_measurement",
            field=models.CharField(
                choices=[("Hours", "Hours"), ("Days", "Days")],
                default="Days",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="minimum_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="plan",
            name="principal",
            field=models.CharField(
                choices=[("Included", "Included"), ("Not Included", "Not Included")],
                default="Included",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="referral",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="duration",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="plan",
            name="investment_name",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="maximum_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="plan",
            name="return_of_investment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
