# Generated by Django 5.2.6 on 2025-10-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "knowledgeprojapp",
            "0004_remove_plan_mimimum_amount_plan_duration_measurement_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="contract_duration_in_days",
            field=models.FloatField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name="payment_id",
            name="contract_duration",
            field=models.FloatField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="return_of_investment",
            field=models.CharField(blank=True, null=True),
        ),
    ]
