# Generated by Django 5.1.3 on 2026-01-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledgeprojapp", "0005_package_contract_duration_in_days_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="return_of_investment",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
